import { sharedOverview, prompt, check, modelPanel, icon, numberSections, shot, links, routeTracker } from "./shared.js";
import { art } from "./art.js";

export const appLab = {
  id: "app",
  name: "Desktop App",
  title: "GitHub Copilot app",
  needsGit: false,
  policy: true,
  tagline: "Sessions, integrated browser, automations, and Canvas in one desktop workspace.",
  mark: icon("home"),
  intro: "The desktop app brings sessions, an integrated browser, GitHub work, automations, and Canvas into one focused workspace. This is the end-to-end app storyline, kept intact as your baseline.",
  preview: "I’ll build a polished, dependency-free quiz and open it in the integrated browser.",
  sections: [
    ["install", "Install", `<section class="lab-section" id="install"><div class="section-kicker">__N__ · Install the app</div><h2>Get set up and say hello.</h2><p class="section-intro">Install the desktop app, authenticate with GitHub, and get familiar with the workspace.</p><div class="install-banner"><div class="install-logo">${icon("bolt")}</div><div><strong>GitHub Copilot app</strong><span>Available for Windows, macOS, and Linux</span></div><a class="button button-primary" href="https://gh.io/app" target="_blank" rel="noopener">Download app ↗</a></div><h3 class="task-heading">Install and configure</h3><ol class="step-list"><li><span class="step-number">1</span><div>Download and install the <a href="https://gh.io/app" target="_blank" rel="noopener">GitHub Copilot app</a>.</div></li><li><span class="step-number">2</span><div>Select <strong>Sign in to GitHub</strong> and authenticate.</div></li><li><span class="step-number">3</span><div>Choose a theme and select <strong>Finish</strong>.</div></li></ol>${check("installed", "App installed and signed in", "Choose a model from the shared preference order below.")}${modelPanel()}<h3 class="task-heading">Find your way around</h3><div class="workspace-list"><div><span>${icon("home")}</span><p><strong>New</strong>Start a session on a project, or pick Chat for a quick question.</p></div><div><span>${icon("work")}</span><p><strong>My work</strong>Browse your GitHub issues and pull requests.</p></div><div><span>${icon("bolt")}</span><p><strong>Automations</strong>Schedule recurring agent work on a repository.</p></div><div><span>${icon("sessions")}</span><p><strong>Customize</strong>Themes, models, and Canvas extensions.</p></div></div><h3 class="task-heading">Try a quick chat</h3><p>Not every question needs a workspace. From <strong>New</strong>, choose <strong>Chat</strong> instead of a project. Chat has no repository attached and cannot edit files, so it is the fastest way to ask a question, get an explanation, or think through an approach before you start a real session.</p>${prompt("How does the GitHub Copilot app use worktrees?", "Ask in Chat")}</section>`],

    ["tour", "Guided tour", `<section class="lab-section tour-start" id="tour"><div class="section-kicker">__N__ · Guided app tour</div><h2>Build it. Ship it. Improve it.</h2><p class="section-intro">Take the space quiz from an empty folder to a reviewed pull request, then put recurring work on autopilot and explore a visual Canvas workflow.</p><div class="route"><span class="done">Create</span><i></i><span>Build</span><i></i><span>Publish</span><i></i><span>Plan</span><i></i><span>Review</span><i></i><span>Automate</span></div></section>`],

    ["workspace", "Create", `<section class="tour-section" id="workspace"><div class="tour-marker"><span>__N__</span></div><div class="tour-content"><div class="tour-label">Create</div><h3>Create the Space Quiz workspace</h3><p>Start a fresh local session with settings that keep you in control.</p><ol class="compact-steps"><li>Choose <strong>New → Open folder</strong>, then an empty <code>space-quiz</code> folder.</li><li>Set <strong>Interactive</strong> mode and choose your preferred model.</li><li>Select <strong>Create</strong>. The session opens empty and waits for your first prompt.</li></ol>${art("appNewSession", "The New screen. Set the folder, the mode, and the agent, then type the first prompt.")}${check("workspace", "Workspace ready")}</div></section>`],

    ["build", "Build & polish", `<section class="tour-section" id="build"><div class="tour-marker"><span>__N__</span></div><div class="tour-content"><div class="tour-label">Build &amp; polish</div><h3>Build in the integrated browser</h3><p>Send one detailed prompt and follow the agent as it creates <code>index.html</code>.</p>${prompt("Create a space exploration quiz with 10 questions, a progress bar, score counter, and colorful animated feedback (green for correct, red shake for wrong). Show a results screen with emoji reaction at the end. Center in a narrow column. Single index.html, no server/dependencies. Polished, sans-serif, 14–16px body, prefers-color-scheme. Open in the integrated browser.")}<p>Play a few questions. Confirm progress, score, correct state, and incorrect shake all work.</p><h4>Polish with the element picker</h4><ol class="compact-steps"><li>Choose the element picker in the browser toolbar.</li><li>Select the quiz heading or answer area.</li><li>Ask for a mission-control feel while preserving light/dark themes.</li></ol>${prompt("Make the selected element feel more like a mission-control display. Keep it accessible and preserve the existing light and dark themes.", "Visual refinement")}${check("built", "Quiz built and polished")}</div></section>`],

    ["session", "Session context", `<section class="tour-section" id="session"><div class="tour-marker"><span>__N__</span></div><div class="tour-content"><div class="tour-label">Context</div><h3>Read the session header</h3><p>Now that a session exists and has done real work, there is something to inspect. The session details tell you exactly what the agent is pointed at. This is not a panel to stare at constantly, but everything in it matters when a result surprises you.</p>${art("appSession", "The session details carry the folder, branch, mode, and how much of the context window is used. There is no model here; that is chosen per request in the composer.")}<ol class="compact-steps"><li>Confirm the <strong>folder</strong> and <strong>branch</strong> are the ones you think you are editing.</li><li>Confirm the <strong>mode</strong>: Interactive asks before acting, Autopilot keeps going, Plan writes no files.</li><li>Check <strong>context usage</strong>. As it climbs, the agent has less room for your actual task, and that is your cue to start a fresh session.</li></ol><div class="callout"><div class="callout-icon">${icon("context")}</div><div><strong>Most bad results are context problems</strong><p>Wrong branch, wrong folder, or a context window that is nearly full explains far more surprises than a bad prompt does.</p></div></div>${check("context", "Session context inspected")}</div></section>`],

    ["test", "Test", `<section class="tour-section" id="test"><div class="tour-marker"><span>__N__</span></div><div class="tour-content"><div class="tour-label">Test</div><h3>Test before Git writes anything</h3><p>The integrated browser is a real browser, so the agent can drive the quiz and report what actually happened rather than what it intended.</p>${prompt("Run a browser-level smoke test for the quiz in the integrated browser. Check keyboard navigation, score updates, correct and incorrect feedback, and the results screen. Fix any failures, then report what passed.", "Test the behavior")}<ol class="compact-steps"><li>Watch the integrated browser as it runs through the questions.</li><li>Fix failures and rerun until everything passes.</li><li>Only once build and test are green, move on. Nothing has been written to Git yet, and the next step is <code>/init</code>, which reads the project as it stands.</li></ol>${check("tested", "Build and test passed")}</div></section>`],

    ["instructions", "Project instructions", `<section class="tour-section" id="instructions"><div class="tour-marker"><span>__N__</span></div><div class="tour-content"><div class="tour-label">Instructions</div><h3>Capture the rules with <code>/init</code></h3><p>Now that the quiz is built and polished, lock in how future sessions should treat this project.</p><ol class="compact-steps"><li>Run <code>/init</code> in the app session.</li><li>Review the generated agent instructions file before accepting it.</li><li>Trim it to guidance that actually reflects this project: single file, no dependencies, accessible, browser-tested.</li></ol><div class="warning"><strong>Why after polishing?</strong><span><code>/init</code> reads the project as it exists right now. Running it once the quiz is built and tested produces instructions that describe real code instead of an empty folder.</span></div><div class="callout"><div class="callout-icon">${icon("context")}</div><div><strong>Make it yours</strong><p>This file is not only for facts about the project. Add the specifics you would otherwise repeat in every prompt: how you like code written, naming conventions, which libraries to avoid, how much commenting you want. Every future session reads it before it reads you.</p></div></div>${check("instructions", "Agent instructions reviewed")}</div></section>`],

    ["publish", "Publish", `<section class="tour-section" id="publish"><div class="tour-marker"><span>__N__</span></div><div class="tour-content"><div class="tour-label">Publish</div><h3>Publish the local project</h3><p>Turn the experiment into a public GitHub repository.</p>${prompt("Initialize this folder as a Git repository, create an initial commit, and create a new public GitHub repository named space-quiz in my account. Push the current branch and set it as the default branch. Refresh the project within this app so the GitHub project is linked.")}<div class="warning"><strong>Review before approving</strong><span>The agent will ask for confirmation before creating a repository or pushing code.</span></div>${check("published", "Repository published")}</div></section>`],

    ["backlog", "Issues & sessions", `<section class="tour-section" id="backlog"><div class="tour-marker"><span>__N__</span></div><div class="tour-content"><div class="tour-label">Issues &amp; sessions</div><h3>Build a backlog in My work</h3><p>Ask the agent to turn product ideas into focused work items.</p>${prompt("Review the space quiz and suggest three focused feature ideas that could each be completed in a short session. Create a separate GitHub issue for each idea with a clear title, user-focused description, and acceptance criteria. Do not implement them yet.", "Create three issues")}${shot("app-my-work", "The My work view in the Copilot app listing open issues and pull requests", "My work pulls your GitHub issues and pull requests into the app.")}<ol class="compact-steps"><li>Open one issue in <strong>My work</strong> and select <strong>New session</strong>.</li><li>Choose a <strong>new worktree</strong>, Interactive mode, and your preferred model.</li><li>Review the diff and verify the feature in the integrated browser.</li></ol>${prompt("Implement this issue completely. Keep the single-file, dependency-free design, test the behavior in the integrated browser, and summarize the changes when finished.", "Implement the issue")}<p>When it reports back, do not take its word for it. Open the right-side flyout and select the <strong>Changes</strong> tab to read the diff yourself, then verify the feature in the integrated browser.</p>${art("appChanges", "The Changes tab lists every file the session touched, with the diff inline.")}${check("issue", "Issue implemented, diff reviewed, and verified")}</div></section>`],

    ["plan", "Plan mode", `<section class="tour-section" id="plan"><div class="tour-marker"><span>__N__</span></div><div class="tour-content"><div class="tour-label">Plan mode</div><h3>Agree on the approach before any code changes</h3><p>Not every issue should start with edits. Plan mode researches the project, proposes an approach, and waits for your approval.</p><ol class="compact-steps"><li>Open a <strong>second issue</strong> from <strong>My work</strong> and select <strong>New session</strong>.</li><li>In the session configuration, choose <strong>Plan</strong> instead of Interactive or Autopilot.</li><li>Send the issue to the agent and let it investigate without changing files.</li><li>Read the proposed plan, request changes if something is missing, then approve it.</li><li>On approval, choose whether the session continues in <strong>Interactive</strong> or <strong>Autopilot</strong> mode.</li></ol>${prompt("Plan how to implement this issue. Investigate the existing quiz, list the files you would change, call out risks to accessibility and the single-file constraint, and stop before making any edits.", "Ask for a plan")}<div class="callout"><div class="callout-icon">${icon("plan")}</div><div><strong>When plan mode pays off</strong><p>Use it for anything ambiguous, cross-cutting, or expensive to undo. The cheapest place to fix a bad approach is before the first edit.</p></div></div>${check("plan", "Plan reviewed and approved")}</div></section>`],

    ["review", "Review", `<section class="tour-section" id="review-loop"><div class="tour-marker"><span>__N__</span></div><div class="tour-content"><div class="tour-label">Review</div><h3>Inspect changes and complete the Copilot review loop</h3><ol class="compact-steps"><li>Open the right-side flyout and select the <strong>Changes</strong> tab to inspect the files changed in the session.</li><li>Select <strong>Create PR</strong> in the session toolbar.</li><li>Request Copilot from the Reviewers menu.</li><li>Read every comment, use Copilot <strong>Fix</strong> for actionable feedback, retest, reply, and resolve.</li><li>Turn on <strong>Agent Merge</strong> for the pull request to let the agent keep it healthy: it addresses review comments, fixes failing checks, and resolves conflicts as they appear, then merges once everything is green.</li></ol>${check("reviewed", "Pull request reviewed")}</div></section>`],

    ["automation", "Automate", `<section class="tour-section" id="automation"><div class="tour-marker"><span>__N__</span></div><div class="tour-content"><div class="tour-label">Automate</div><h3>Schedule weekly issue triage</h3>${shot("app-automations", "The Automations view in the Copilot app with a weekly schedule", "Automations run the same prompt on a schedule, in their own session.")}<ol class="compact-steps"><li>Open <strong>Automations</strong> and choose a weekly automation.</li><li>Use Autopilot with Auto, select <code>space-quiz</code>, then Create and run.</li></ol>${prompt("Reviews the latest GitHub issues created and are open in the last week, and provide a summary table ranked by severity and priority", "Weekly automation")}${check("automated", "Automation created and run")}</div></section>`],

    ["remote", "Go remote (optional)", `<section class="tour-section" id="remote"><div class="tour-marker"><span>__N__</span></div><div class="tour-content"><div class="tour-label">Go remote</div><h3>Continue a session remotely</h3><p>Optional, and worth saving until the local loop feels natural. <code>/remote</code> continues the session you are already in on GitHub, so you can step away from your machine and keep following it.</p><ol class="compact-steps"><li>Open a session that has work in progress.</li><li>Run <code>/remote</code> to continue that session remotely.</li><li>Select the link it returns to open the remote session in your browser.</li><li>Follow its progress from there, then review the changes exactly like any other pull request.</li></ol><div class="callout"><div class="callout-icon">${icon("bolt")}</div><div><strong>This is not delegation</strong><p>You are not handing the task to a different agent. It is the same session, continuing somewhere you can reach from any device.</p></div></div>${check("remote", "Remote session explored")}</div></section>`],

    ["canvas", "Canvas", `<section class="tour-section last" id="canvas"><div class="tour-marker"><span>__N__</span></div><div class="tour-content"><div class="tour-label">Canvas</div><h3>Kick off work from a Kanban Canvas</h3><p>Install a Canvas extension, move an issue card, and confirm the generated session has the issue context ready.</p><ol class="compact-steps"><li>Browse the <a href="https://awesome-copilot.github.com/extensions/" target="_blank" rel="noopener">Canvas extensions gallery</a>.</li><li>Install the Repository Issues Kanban extension.</li><li>Open the board, move an issue into active work, and follow the generated session.</li></ol>${art("appCanvas", "Drag an issue card into a lane and the Canvas hands that issue to a new session.")}${check("canvas", "Canvas extension explored")}</div></section>`]
  ],

  renderResources() {
    return `<section class="lab-section finish-section" id="resources"><div class="section-kicker">${String(this.sections.length + 2).padStart(2, "0")} · Review &amp; resources</div><div class="finish-badge">${icon("ship")}</div><h2>You’ve completed the app tour.</h2><p class="section-intro">You built, published, planned, reviewed, automated, went remote, and explored a shared Canvas workflow.</p><div class="recap-grid"><div><span>01</span><strong>Created</strong><small>A local project</small></div><div><span>02</span><strong>Built</strong><small>A live browser quiz</small></div><div><span>03</span><strong>Shipped</strong><small>A reviewed PR</small></div></div>${check("complete", "Mark the lab complete", "Progress is saved for this product in this browser.")}${routeTracker()}${links("Keep going", [
      ["Download the app", "https://gh.io/app", "Windows, macOS, and Linux builds"],
      ["Copilot app docs", "https://docs.github.com/copilot", "Sessions, modes, and everything the app can do"],
      ["Canvas extensions gallery", "https://awesome-copilot.github.com/extensions/", "Install a Canvas or build your own"],
      ["Copilot plans", "https://github.com/features/copilot/plans", "Free, Pro, Business, and Enterprise"],
      ["Best practices", "https://docs.github.com/copilot/get-started/best-practices", "Write prompts that hold up on real code"]
    ])}</section>`;
  },

  render() {
    return sharedOverview(this) + numberSections(this.sections) + this.renderResources();
  }
};
