import { sharedOverview, prompt, check, modelPanel, icon } from "./shared.js";

export const appLab = {
  id: "app",
  name: "Desktop App",
  title: "GitHub Copilot app",
  needsGit: false,
  policy: true,
  intro: "The desktop app brings sessions, an integrated browser, GitHub work, automations, and Canvas into one focused workspace. This is the end-to-end app storyline, kept intact as your baseline.",
  preview: "I’ll build a polished, dependency-free quiz and open it in the integrated browser.",
  sections: [
    ["install", "Install", `<section class="lab-section" id="install"><div class="section-kicker">02 · Install the app</div><h2>Get set up and say hello.</h2><p class="section-intro">Install the desktop app, authenticate with GitHub, and get familiar with the workspace.</p><div class="install-banner"><div class="install-logo">${icon("bolt")}</div><div><strong>GitHub Copilot app</strong><span>Available for Windows, macOS, and Linux</span></div><a class="button button-primary" href="https://gh.io/app" target="_blank" rel="noopener">Download app ↗</a></div><h3 class="task-heading">Install and configure</h3><ol class="step-list"><li><span class="step-number">1</span><div>Download and install the <a href="https://gh.io/app" target="_blank" rel="noopener">GitHub Copilot app</a>.</div></li><li><span class="step-number">2</span><div>Select <strong>Sign in to GitHub</strong> and authenticate.</div></li><li><span class="step-number">3</span><div>Choose a theme and select <strong>Finish</strong>.</div></li></ol>${check("installed", "App installed and signed in", "Choose a model from the shared preference order below.")}${modelPanel()}<h3 class="task-heading">Find your way around</h3><div class="workspace-list"><div><span>${icon("home")}</span><p><strong>Home</strong>Choose a project and configure a session.</p></div><div><span>${icon("sessions")}</span><p><strong>Sessions</strong>Run agents in isolated workspaces.</p></div><div><span>${icon("work")}</span><p><strong>My work</strong>Browse issues and pull requests.</p></div><div><span>${icon("bolt")}</span><p><strong>Automations &amp; Canvas</strong>Optional shared workflows unique to the app.</p></div></div>${prompt("How does the GitHub Copilot app use worktrees?", "Try a quick chat")}</section>`],

    ["tour", "Guided tour", `<section class="lab-section tour-start" id="tour"><div class="section-kicker">03 · Guided app tour</div><h2>Build it. Ship it. Improve it.</h2><p class="section-intro">Take the space quiz from an empty folder to a reviewed pull request, then put recurring work on autopilot and explore a visual Canvas workflow.</p><div class="route"><span class="done">Create</span><i></i><span>Build</span><i></i><span>Publish</span><i></i><span>Plan</span><i></i><span>Review</span><i></i><span>Automate</span></div></section>`],

    ["workspace", "Create", `<section class="tour-section" id="workspace"><div class="tour-marker"><span>01</span></div><div class="tour-content"><div class="tour-label">Create</div><h3>Create the Space Quiz workspace</h3><p>Start a fresh local session with settings that keep you in control.</p><ol class="compact-steps"><li>Choose <strong>New → Local folder or repository</strong>, then an empty <code>space-quiz</code> folder.</li><li>Set <strong>Interactive</strong> mode and choose your preferred model.</li><li>Notice the <strong>session header context</strong>: it shows the active folder, branch, and model.</li></ol>${check("workspace", "Workspace ready")}</div></section>`],

    ["build", "Build & polish", `<section class="tour-section" id="build"><div class="tour-marker"><span>02</span></div><div class="tour-content"><div class="tour-label">Build &amp; polish</div><h3>Build in the integrated browser</h3><p>Send one detailed prompt and follow the agent as it creates <code>index.html</code>.</p>${prompt("Create a space exploration quiz with 10 questions, a progress bar, score counter, and colorful animated feedback (green for correct, red shake for wrong). Show a results screen with emoji reaction at the end. Center in a narrow column. Single index.html, no server/dependencies. Polished, sans-serif, 14–16px body, prefers-color-scheme. Open in the integrated browser.")}<p>Play a few questions. Confirm progress, score, correct state, and incorrect shake all work.</p><h4>Polish with the element picker</h4><ol class="compact-steps"><li>Choose the element picker in the browser toolbar.</li><li>Select the quiz heading or answer area.</li><li>Ask for a mission-control feel while preserving light/dark themes.</li></ol>${prompt("Make the selected element feel more like a mission-control display. Keep it accessible and preserve the existing light and dark themes.", "Visual refinement")}${check("built", "Quiz built and polished")}</div></section>`],

    ["instructions", "Project instructions", `<section class="tour-section" id="instructions"><div class="tour-marker"><span>03</span></div><div class="tour-content"><div class="tour-label">Instructions</div><h3>Capture the rules with <code>/init</code></h3><p>Now that the quiz is built and polished, lock in how future sessions should treat this project.</p><ol class="compact-steps"><li>Run <code>/init</code> in the app session.</li><li>Review the generated agent instructions file before accepting it.</li><li>Trim it to guidance that actually reflects this project: single file, no dependencies, accessible, browser-tested.</li></ol><div class="warning"><strong>Why after polishing?</strong><span><code>/init</code> reads the project as it exists right now. Running it once the quiz is finished produces instructions that describe the real code instead of an empty folder.</span></div>${check("instructions", "Agent instructions reviewed")}</div></section>`],

    ["publish", "Publish", `<section class="tour-section" id="publish"><div class="tour-marker"><span>04</span></div><div class="tour-content"><div class="tour-label">Publish</div><h3>Publish the local project</h3><p>Turn the experiment into a public GitHub repository.</p>${prompt("Initialize this folder as a Git repository, create an initial commit, and create a new public GitHub repository named space-quiz in my account. Push the current branch and set it as the default branch. Refresh the project within this app so the GitHub project is linked.")}<div class="warning"><strong>Review before approving</strong><span>The agent will ask for confirmation before creating a repository or pushing code.</span></div>${check("published", "Repository published")}</div></section>`],

    ["backlog", "Issues & sessions", `<section class="tour-section" id="backlog"><div class="tour-marker"><span>05</span></div><div class="tour-content"><div class="tour-label">Issues &amp; sessions</div><h3>Build a backlog in My work</h3><p>Ask the agent to turn product ideas into focused work items.</p>${prompt("Review the space quiz and suggest three focused feature ideas that could each be completed in a short session. Create a separate GitHub issue for each idea with a clear title, user-focused description, and acceptance criteria. Do not implement them yet.", "Create three issues")}<ol class="compact-steps"><li>Open one issue in <strong>My work</strong> and select <strong>New session</strong>.</li><li>Choose a <strong>new worktree</strong>, Interactive mode, and your preferred model.</li><li>Review the diff and verify the feature in the integrated browser.</li></ol>${prompt("Implement this issue completely. Keep the single-file, dependency-free design, test the behavior in the integrated browser, and summarize the changes when finished.", "Implement the issue")}${check("issue", "Issue implemented and verified")}</div></section>`],

    ["plan", "Plan mode", `<section class="tour-section" id="plan"><div class="tour-marker"><span>06</span></div><div class="tour-content"><div class="tour-label">Plan mode</div><h3>Agree on the approach before any code changes</h3><p>Not every issue should start with edits. Plan mode researches the project, proposes an approach, and waits for your approval.</p><ol class="compact-steps"><li>Open a <strong>second issue</strong> from <strong>My work</strong> and select <strong>New session</strong>.</li><li>In the session configuration, choose <strong>Plan</strong> instead of Interactive or Autopilot.</li><li>Send the issue to the agent and let it investigate without changing files.</li><li>Read the proposed plan, request changes if something is missing, then approve it.</li><li>On approval, choose whether the session continues in <strong>Interactive</strong> or <strong>Autopilot</strong> mode.</li></ol>${prompt("Plan how to implement this issue. Investigate the existing quiz, list the files you would change, call out risks to accessibility and the single-file constraint, and stop before making any edits.", "Ask for a plan")}<div class="callout"><div class="callout-icon">${icon("plan")}</div><div><strong>When plan mode pays off</strong><p>Use it for anything ambiguous, cross-cutting, or expensive to undo. The cheapest place to fix a bad approach is before the first edit.</p></div></div>${check("plan", "Plan reviewed and approved")}</div></section>`],

    ["review", "Review", `<section class="tour-section" id="review-loop"><div class="tour-marker"><span>07</span></div><div class="tour-content"><div class="tour-label">Review</div><h3>Inspect changes and complete the Copilot review loop</h3><ol class="compact-steps"><li>Open the right-side flyout and select the <strong>Changes</strong> tab to inspect the files changed in the session.</li><li>Select <strong>Create PR</strong> in the session toolbar.</li><li>Request Copilot from the Reviewers menu.</li><li>Read every comment, use Copilot <strong>Fix</strong> for actionable feedback, retest, reply, and resolve.</li></ol>${check("reviewed", "Pull request reviewed")}</div></section>`],

    ["automation", "Automate", `<section class="tour-section" id="automation"><div class="tour-marker"><span>08</span></div><div class="tour-content"><div class="tour-label">Automate</div><h3>Schedule weekly issue triage</h3><ol class="compact-steps"><li>Open <strong>Automations</strong> and choose a weekly automation.</li><li>Use Autopilot with Auto, select <code>space-quiz</code>, then Create and run.</li></ol>${prompt("Reviews the latest GitHub issues created and are open in the last week, and provide a summary table ranked by severity and priority", "Weekly automation")}${check("automated", "Automation created and run")}</div></section>`],

    ["remote", "Go remote", `<section class="tour-section" id="remote"><div class="tour-marker"><span>09</span></div><div class="tour-content"><div class="tour-label">Go remote</div><h3>Hand a session off to the cloud</h3><p>Once you are comfortable with the local loop, you can move a session to GitHub and keep following it from a browser.</p><ol class="compact-steps"><li>Open a session that has work in progress.</li><li>Run <code>/remote</code> to hand the session to a GitHub-hosted cloud agent.</li><li>Close your laptop, then check the session’s progress from GitHub on another device.</li><li>Review the changes it produced exactly like any other pull request.</li></ol><div class="callout"><div class="callout-icon">${icon("bolt")}</div><div><strong>Save this for later</strong><p>Remote sessions are most useful for long, well-specified work. Learn the local loop first so you can tell when a task is ready to run unattended.</p></div></div>${check("remote", "Remote session explored")}</div></section>`],

    ["canvas", "Canvas", `<section class="tour-section last" id="canvas"><div class="tour-marker"><span>10</span></div><div class="tour-content"><div class="tour-label">Canvas</div><h3>Kick off work from a Kanban Canvas</h3><p>Install a Canvas extension, move an issue card, and confirm the generated session has the issue context ready.</p><ol class="compact-steps"><li>Browse the <a href="https://awesome-copilot.github.com/extensions/" target="_blank" rel="noopener">Canvas extensions gallery</a>.</li><li>Install the Repository Issues Kanban extension.</li><li>Open the board, move an issue into active work, and follow the generated session.</li></ol>${check("canvas", "Canvas extension explored")}</div></section>`]
  ],

  renderResources() {
    return `<section class="lab-section finish-section" id="resources"><div class="section-kicker">04 · Review &amp; resources</div><div class="finish-badge">${icon("ship")}</div><h2>You’ve completed the app tour.</h2><p class="section-intro">You built, published, planned, reviewed, automated, went remote, and explored a shared Canvas workflow.</p><div class="recap-grid"><div><span>01</span><strong>Created</strong><small>A local project</small></div><div><span>02</span><strong>Built</strong><small>A live browser quiz</small></div><div><span>03</span><strong>Shipped</strong><small>A reviewed PR</small></div></div>${check("complete", "Mark the lab complete", "Progress is saved for this product in this browser.")}</section>`;
  },

  render() {
    return sharedOverview(this) + this.sections.map(([, , html]) => html).join("") + this.renderResources();
  }
};
