import { sharedOverview, prompt, check, modelPanel, icon, numberSections, links } from "./shared.js";
import { art } from "./art.js";

export const cliLab = {
  id: "cli",
  name: "CLI",
  title: "GitHub Copilot CLI",
  needsGit: true,
  policy: true,
  tagline: "An agent in your terminal: slash commands, parallel sessions, worktrees.",
  mark: icon("terminal"),
  intro: "Learn the terminal-first loop: build and review diffs before Git writes anything, run sessions side by side, plan before you edit, then create and merge the pull request without leaving your shell.",
  preview: "I’ll work in the terminal, review every diff, and plan the change before publishing.",
  sections: [
    ["setup", "Set up", `<section class="lab-section" id="setup"><div class="section-kicker">__N__ · Set up the CLI</div><h2>Put an agent in your terminal.</h2><p class="section-intro">Install Copilot CLI, sign in, and make your first request from an empty folder.</p><ol class="step-list"><li><span class="step-number">1</span><div>Install <a href="https://docs.github.com/copilot/how-tos/set-up/install-copilot-cli" target="_blank" rel="noopener">GitHub Copilot CLI</a> for your platform.</div></li><li><span class="step-number">2</span><div>Create and enter the project folder: <code>mkdir space-quiz &amp;&amp; cd space-quiz</code>.</div></li><li><span class="step-number">3</span><div>Run <code>copilot</code>, sign in, and trust the folder when prompted.</div></li><li><span class="step-number">4</span><div>Run <code>/model</code> and choose from the shared preference order below.</div></li><li><span class="step-number">5</span><div>Optional but recommended: install the <a href="https://cli.github.com/" target="_blank" rel="noopener">GitHub CLI</a> (<code>gh</code>) so the agent can create repositories and pull requests for you.</div></li></ol>${art("cliWelcome", "The CLI opens with a trust prompt and a few starting commands, including <code>/model</code>.")}${check("installed", "CLI installed and signed in")}${modelPanel()}<p class="note">Type <code>/</code> at any time to browse every available command, or <code>/help</code> for the full reference.</p></section>`],

    ["build", "Build", `<section class="tour-section" id="build"><div class="tour-marker"><span>__N__</span></div><div class="tour-content"><div class="tour-label">Build</div><h3>Build the quiz from the terminal</h3><p>Ask for the whole project in one detailed request, then review what the agent proposes before approving it.</p>${prompt("Create a space exploration quiz with 10 questions, a progress bar, score counter, and colorful animated feedback (green for correct, red shake for wrong). Show a results screen with an emoji reaction at the end. Single index.html, no server or dependencies. Accessible, keyboard-navigable, and respects prefers-color-scheme.", "Build the quiz")}<ol class="compact-steps"><li>Read the proposed plan and approve the file changes.</li><li>Open <code>index.html</code> in a browser and play a few questions. Run <code>!open index.html</code> on macOS, or <code>!start index.html</code> on Windows, to launch it from the session.</li></ol><h4>Make a small change, then check it</h4><p>Ask for one focused refinement so you can see how a scoped request behaves.</p>${prompt("The results screen feels flat. Give it a stronger sense of arrival: animate the score counting up and make the emoji reaction larger. Change nothing else.", "One focused change")}<ol class="compact-steps"><li>Reload the page in your browser and play through to the end.</li><li>Nothing is in Git yet, so there is nothing to diff against. That changes in a moment.</li></ol>${check("built", "Quiz built and refined")}</div></section>`],

    ["instructions", "Project instructions", `<section class="tour-section" id="instructions"><div class="tour-marker"><span>__N__</span></div><div class="tour-content"><div class="tour-label">Instructions</div><h3>Capture the rules with <code>/init</code></h3><p>With a working quiz on disk, generate agent instructions that describe the real project.</p><ol class="compact-steps"><li>Run <code>/init</code> in the session.</li><li>Review the generated instructions file before accepting it.</li><li>Keep only guidance that matches this project: single file, no dependencies, accessible, browser-tested.</li></ol><div class="warning"><strong>Order matters</strong><span><code>/init</code> reads the project as it exists right now. Running it after the quiz is built and polished produces instructions grounded in real code.</span></div><div class="callout"><div class="callout-icon">${icon("context")}</div><div><strong>Make it yours</strong><p>This file is not only for facts about the project. Add the specifics you would otherwise repeat in every prompt: how you like code written, naming conventions, which libraries to avoid, how much commenting you want. Every future session reads it before it reads you.</p></div></div>${check("instructions", "Agent instructions reviewed")}</div></section>`],

    ["publish", "Publish", `<section class="tour-section" id="publish"><div class="tour-marker"><span>__N__</span></div><div class="tour-content"><div class="tour-label">Publish</div><h3>Initialize, commit, and publish</h3><p>You can ask for this in one prompt, or run it yourself. Do it both ways once and you will know exactly what the agent is doing on your behalf.</p>${prompt("Initialize this folder as a Git repository, create an initial commit, and create a new public GitHub repository named space-quiz in my account. Push the current branch and set it as the default branch.", "Option A · ask for it")}<h4>Option B · run it yourself</h4><p>Prefix each command with <code>!</code> to run it from inside the session, or drop to your own terminal.</p><pre class="command-block"><code>!git init -b main
!git add .
!git commit -m "Add space quiz"
!gh repo create space-quiz --public --source=. --push</code></pre><ol class="compact-steps"><li>Approve each Git and GitHub action as the agent requests it, or run the commands above.</li><li>Run <code>!git log --oneline</code> to confirm the commit landed.</li><li>Open the repository and confirm <code>index.html</code> is present.</li></ol><p class="note">The last command uses the <a href="https://cli.github.com/" target="_blank" rel="noopener">GitHub CLI</a>. Without it, create the repository on GitHub, then run <code>!git remote add origin &lt;url&gt;</code> and <code>!git push -u origin main</code>.</p>${check("published", "Repository published")}</div></section>`],

    ["issues", "Issues & sessions", `<section class="tour-section" id="issues"><div class="tour-marker"><span>__N__</span></div><div class="tour-content"><div class="tour-label">Issues &amp; sessions</div><h3>Work on issues in parallel</h3><p>Keep the backlog and the implementation loop in the terminal, and open separate sessions for independent work.</p>${prompt("Review the space quiz and create three focused GitHub issues with clear titles, user-focused descriptions, and acceptance criteria. Do not implement them yet.", "Create three issues")}<h4>First issue · work it in this session</h4><ol class="compact-steps"><li>Open the <strong>Issues</strong> tab to list and inspect the new issues.</li><li>Highlight the first issue and press <strong>c</strong> to add it to the chat as context.</li><li>Ask the agent to implement it.</li></ol><h4>Now <code>/diff</code> earns its keep</h4><p>The project is published, so there is a known-good version to compare against. <code>/diff</code> shows precisely what this issue changed on top of it, which is exactly what you are about to ask someone to review.</p><ol class="compact-steps"><li>Run <code>/diff</code> and read every changed file.</li><li>Ask for a fix for anything that looks wrong, then run <code>/diff</code> again.</li><li>Run <code>!git status</code> or <code>!git diff</code> whenever you want to inspect Git directly.</li></ol>${art("cliSessions", "The side panel keeps every session one keystroke away, each with its own branch or worktree.")}<h4>Second issue · work it in parallel</h4><ol class="compact-steps"><li>Press the <strong>left arrow</strong> to open the session side panel.</li><li>Start another session for the second issue without losing this one.</li><li>In the new session, run <code>/worktree</code> so it gets an isolated worktree instead of branching in place. Both sessions can now run at once without stepping on each other.</li><li>Add the second issue to that session with <strong>c</strong>.</li><li>Leave it there for now: the next step plans this one before writing any code.</li></ol>${art("cliWorktree", "<code>/worktree</code> moves this session into its own checkout on its own branch, so the first session keeps working undisturbed.")}${check("issue", "First issue implemented, second session running in a worktree")}</div></section>`],

    ["plan", "Plan mode", `<section class="tour-section" id="plan"><div class="tour-marker"><span>__N__</span></div><div class="tour-content"><div class="tour-label">Plan mode</div><h3>Agree on the approach before any edits</h3><p>You already have a second session running in its own worktree. Do not start with code there. Plan mode researches the project and proposes an approach while leaving your files untouched.</p><ol class="compact-steps"><li>Switch to the <strong>second session</strong> you opened in the previous step.</li><li>Run <code>/plan</code> to switch that session into plan mode.</li><li>Send the issue and let the agent investigate without editing anything.</li><li>Read the plan, push back on anything missing, then approve it.</li><li>The session continues into implementation with the approved plan as its brief.</li></ol>${prompt("Plan how to implement this issue. Investigate the existing quiz, list the files you would change, call out risks to accessibility and the single-file constraint, and stop before making any edits.", "Ask for a plan")}<div class="callout"><div class="callout-icon">${icon("plan")}</div><div><strong>When plan mode pays off</strong><p>Use it for anything ambiguous, cross-cutting, or expensive to undo. The cheapest place to fix a bad approach is before the first edit.</p></div></div>${check("plan", "Plan reviewed and approved")}</div></section>`],

    ["context", "Context", `<section class="tour-section" id="context"><div class="tour-marker"><span>__N__</span></div><div class="tour-content"><div class="tour-label">Context</div><h3>Know what the agent can see</h3><p>Terminal commands make context visible and intentional.</p><ol class="compact-steps"><li>Run <code>/context</code> to inspect files, instructions, and conversation history.</li><li>Check how much of the window each part is consuming.</li><li>Run <code>/clear</code> to start fresh when the conversation has drifted.</li><li>Add the right file back before asking for another change.</li></ol>${art("cliContext", "<code>/context</code> shows exactly what is filling the context window, and how much room is left.")}${check("context", "Context inspected")}</div></section>`],

    ["resume", "Resume & remote", `<section class="tour-section" id="resume"><div class="tour-marker"><span>__N__</span></div><div class="tour-content"><div class="tour-label">Resume</div><h3>Leave a session and come back later</h3><p>Sessions can be paused without losing their conversation or workspace context.</p><ol class="compact-steps"><li>Exit the current CLI session when you are ready to switch tasks.</li><li>From a terminal, run <code>copilot --resume</code> to pick a previous session.</li><li>Inside Copilot CLI, use <code>/resume</code> to jump between sessions without leaving the CLI.</li><li>Confirm the restored session still has the expected files, issue context, and model.</li></ol><h4>Optional · continue a session remotely</h4><p>Say you are deep in one of these sessions and want to keep it going after you close the laptop. Run <code>/remote</code> to continue <em>that same session</em> on GitHub, then select the link it returns to open and browse it in your browser. It is not delegation and it is not required for this lab, so treat it as something to try once the local loop feels natural.</p>${check("resume", "Session resumed")}</div></section>`],

    ["review", "Pull request", `<section class="tour-section" id="review"><div class="tour-marker"><span>__N__</span></div><div class="tour-content"><div class="tour-label">Pull request</div><h3>Create, review, and merge from the CLI</h3><p>Finish the development loop without switching to a desktop UI.</p><ol class="compact-steps"><li>Run <code>/diff</code> to inspect the changed files one last time.</li><li>Ask Copilot to create a pull request from the current branch, or run <code>/pr create</code>.</li><li>Open the <strong>Pull requests</strong> tab to check the title, description, files, and status checks.</li><li>Fix actionable feedback, check it in the browser, and reply with what changed.</li><li>When it is ready, run <code>/pr agentmerge</code> to validate the pull request and merge it after the required confirmations and checks pass.</li></ol>${check("reviewed", "Pull request reviewed and merged")}</div></section>`],

    ["delegate", "Delegate & cloud", `<section class="tour-section last" id="delegate"><div class="tour-marker"><span>__N__</span></div><div class="tour-content"><div class="tour-label">Go further</div><h3>Delegate work once you trust the loop</h3><p>You have shipped the feature. Now that you know what good output looks like, a whole new idea is worth running beside you rather than in front of you. Here is one: a <strong>shareable mission report</strong> that turns a finished run into a card the player can post.</p>${prompt("Delegate this: add a shareable mission report to the space quiz. At the end of a run, generate a compact summary card with the score, a rank title based on the percentage, and the slowest question. Add a Copy result button that puts a short plain-text version on the clipboard. Keep it in the single index.html with no dependencies, keep it keyboard accessible, and report back with what changed.", "Delegate a new feature")}<ol class="compact-steps"><li>Run <code>/delegate</code> and hand over the mission report task.</li><li>Keep working in the primary session while it runs.</li><li>Compare the delegated result against your session before accepting it.</li><li>For a larger, well-specified issue, start a <strong>cloud session</strong> and follow its progress from the CLI.</li></ol>${check("delegate", "Delegated work reviewed")}</div></section>`]
  ],

  renderResources() {
    return `<section class="lab-section finish-section" id="resources"><div class="section-kicker">${String(this.sections.length + 2).padStart(2, "0")} · Review &amp; resources</div><div class="finish-badge">${icon("terminal")}</div><h2>You’ve completed the CLI route.</h2><p class="section-intro">You built, reviewed diffs, published, ran sessions in parallel, planned before editing, delegated, resumed, and merged a pull request without leaving the terminal.</p><div class="recap-grid"><div><span>01</span><strong>Built</strong><small>Diff reviewed</small></div><div><span>02</span><strong>Planned</strong><small>Before editing</small></div><div><span>03</span><strong>Merged</strong><small>With /pr agentmerge</small></div></div>${check("complete", "Mark the lab complete", "Progress is saved for Copilot CLI only.")}${links("Keep going", [
      ["Install Copilot CLI", "https://docs.github.com/copilot/how-tos/set-up/install-copilot-cli", "Setup for macOS, Windows, and Linux"],
      ["CLI documentation", "https://docs.github.com/copilot/concepts/agents/about-copilot-cli", "Every slash command and flag"],
      ["GitHub CLI", "https://cli.github.com/", "gh, for repositories and pull requests"],
      ["Install Git", "https://git-scm.com/downloads", "Required for this route"],
      ["Best practices", "https://docs.github.com/copilot/get-started/best-practices", "Write prompts that hold up on real code"],
      ["Copilot plans", "https://github.com/features/copilot/plans", "Free, Pro, Business, and Enterprise"]
    ])}</section>`;
  },

  render() {
    return sharedOverview(this) + numberSections(this.sections) + this.renderResources();
  }
};
