import { sharedOverview, prompt, check, modelPanel } from "./shared.js";
export const cliLab = {
  id: "cli", name: "Copilot CLI", title: "GitHub Copilot CLI",
  intro: "Learn the terminal-first loop: delegate work, inspect a cloud session, bring context back with /remote and /context, then test before Git writes anything.",
  preview: "I’ll work in the terminal, delegate a focused task, and run the tests before publishing.",
  sections: [
    ["setup", "Set up", `<section class="lab-section" id="setup"><div class="section-kicker">02 · Set up the CLI</div><h2>Put an agent in your terminal.</h2><p class="section-intro">Install Copilot CLI, sign in, and make your first request. There is no Node.js prerequisite.</p><ol class="step-list"><li><span class="step-number">1</span><div>Install <a href="https://github.com/features/copilot" target="_blank" rel="noopener">GitHub Copilot CLI</a> for your platform.</div></li><li><span class="step-number">2</span><div>Run <code>copilot</code>, sign in, and open an empty <code>space-quiz</code> folder.</div></li><li><span class="step-number">3</span><div>Choose the shared model preference order below.</div></li></ol>${check("installed", "CLI installed and signed in")}${modelPanel()}</section>`],
    ["delegate", "Delegate", `<section class="tour-section" id="delegate"><div class="tour-marker"><span>01</span></div><div class="tour-content"><div class="tour-label">Delegate</div><h3>Hand off a focused task</h3><p>Use the CLI to ask for work, then delegate a bounded follow-up instead of losing your place.</p>${prompt("Create the single-file space quiz in index.html. Keep it dependency-free, accessible, and ready to run in a browser.", "Build the quiz")}<ol class="compact-steps"><li>Review the proposed plan and changes.</li><li>Use <code>/delegate</code> to send a focused accessibility or test task to another agent.</li><li>Compare the result with the primary session before accepting it.</li></ol>${check("delegate", "Delegated work reviewed")}</div></section>`],
    ["cloud", "Cloud session", `<section class="tour-section" id="cloud"><div class="tour-marker"><span>02</span></div><div class="tour-content"><div class="tour-label">Cloud session</div><h3>Continue work away from your machine</h3><p>Start a cloud session for a small issue, then follow its progress from the CLI.</p><ol class="compact-steps"><li>Create a GitHub issue describing one quiz improvement.</li><li>Start a <strong>cloud session</strong> for the issue.</li><li>Review the proposed changes and bring the session back into your workflow.</li></ol>${check("cloud", "Cloud session explored")}</div></section>`],
    ["context", "Context", `<section class="tour-section" id="context"><div class="tour-marker"><span>03</span></div><div class="tour-content"><div class="tour-label">Context</div><h3>Know what the agent can see</h3><p>Terminal commands make context visible and intentional.</p><ol class="compact-steps"><li>Run <code>/remote</code> to inspect the connected GitHub remote.</li><li>Run <code>/context</code> to inspect files, instructions, and conversation context.</li><li>Correct or add context before asking for another change.</li></ol>${check("context", "Remote and context inspected")}</div></section>`],
    ["test", "Test & init", `<section class="tour-section" id="test"><div class="tour-marker"><span>04</span></div><div class="tour-content"><div class="tour-label">Test &amp; init</div><h3>Test and define the project before Git writes</h3><p>Build and test the quiz before the CLI initializes Git or publishes anything.</p>${prompt("Run a browser-level smoke test for the quiz. Check keyboard navigation, score updates, correct and incorrect feedback, and the results screen. Report failures and fix them before continuing.", "Test the behavior")}<ol class="compact-steps"><li>Run the test command or browser smoke test.</li><li>Fix failures and rerun until green.</li><li>After the base quiz works, run <code>/init</code> to create project agent instructions.</li><li>Review the generated instructions, then initialize Git, commit, create the remote, and push.</li></ol>${check("tested", "Build/test passed and /init reviewed before Git init")}</div></section>`],
    ["publish", "Publish", `<section class="tour-section" id="publish"><div class="tour-marker"><span>05</span></div><div class="tour-content"><div class="tour-label">Publish</div><h3>Initialize, commit, and publish</h3><p>Now that the project is tested, use Git and GitHub to share it.</p><ol class="compact-steps"><li>Initialize Git and create an initial commit.</li><li>Create a public <code>space-quiz</code> repository and push the current branch.</li><li>Open the repository and confirm the tested file is present.</li></ol>${check("published", "Repository published")}</div></section>`],
    ["issues", "Issues & sessions", `<section class="tour-section" id="issues"><div class="tour-marker"><span>06</span></div><div class="tour-content"><div class="tour-label">Issues &amp; sessions</div><h3>Work on issues in parallel</h3><p>Use the CLI to keep the backlog and implementation loop in the terminal, while opening separate sessions for independent work.</p>${prompt("Review the space quiz and create three focused GitHub issues with clear titles, user-focused descriptions, and acceptance criteria. Do not implement them yet.", "Create three issues")}<ol class="compact-steps"><li>Use the CLI issue workflow to list and inspect the new issues.</li><li>Choose one issue, then press the <strong>left arrow</strong> to open the session side panel.</li><li>Use the panel to start another session for a different issue without losing the current session.</li><li>In the new session, use <code>/worktree</code> when you want an isolated worktree instead of creating a branch in the current workspace.</li><li>Run <code>!git status</code>, <code>!git diff</code>, or another approved shell command when you need to inspect Git directly.</li><li>Run the browser smoke test again before opening a pull request.</li></ol>${check("issue", "Issue implemented and verified")}</div></section>`],
    ["resume", "Resume", `<section class="tour-section" id="resume"><div class="tour-marker"><span>07</span></div><div class="tour-content"><div class="tour-label">Resume</div><h3>Leave a session and come back later</h3><p>Sessions can be paused without losing their conversation or workspace context.</p><ol class="compact-steps"><li>Exit the current CLI session when you are ready to switch tasks.</li><li>From a terminal, run <code>copilot --resume</code> to choose a previous session.</li><li>Inside Copilot CLI, use <code>/resume</code> to return to another session without leaving the CLI.</li><li>Confirm the restored session still has the expected files, issue context, and model.</li></ol>${check("resume", "Session resumed")}</div></section>`],
    ["review", "Pull request", `<section class="tour-section last" id="review"><div class="tour-marker"><span>08</span></div><div class="tour-content"><div class="tour-label">Pull request</div><h3>Create, review, and merge from the CLI</h3><p>Finish the development loop without switching to a desktop UI.</p><ol class="compact-steps"><li>Run <code>/diff</code> to see the files changed in the current session and inspect the proposed work before opening the PR.</li><li>Ask Copilot to create a pull request from the current branch, or run <code>/pr create</code>.</li><li>Inspect the title, description, changed files, checks, and review status.</li><li>Fix actionable feedback, rerun the quiz smoke test, and reply with what changed.</li><li>When the pull request is ready, run <code>/pr agentmerge</code> to validate the pull request and merge it after the required confirmations and checks pass.</li></ol>${check("reviewed", "Pull request reviewed and merged")}</div></section>`]
  ],
  renderResources() { return `<section class="lab-section finish-section" id="resources"><div class="section-kicker">03 · Review & resources</div><div class="finish-badge">✦</div><h2>You’ve completed the CLI route.</h2><p class="section-intro">You delegated, explored a cloud session, inspected context, tested, and published from the terminal.</p>${check("complete", "Mark the lab complete", "Progress is saved for Copilot CLI only.")}</section>`; },
  render() { return sharedOverview(this.title, this.intro) + this.sections.map(([, , html]) => html).join("") + this.renderResources(); }
};
