import { sharedOverview, prompt, check, modelPanel, icon, figure } from "./shared.js";

export const cliLab = {
  id: "cli",
  name: "CLI",
  title: "GitHub Copilot CLI",
  needsGit: true,
  policy: true,
  intro: "Learn the terminal-first loop: build and test before Git writes anything, run sessions side by side, plan before you edit, then create and merge the pull request without leaving your shell.",
  preview: "I’ll work in the terminal, plan the change, and run the tests before publishing.",
  sections: [
    ["setup", "Set up", `<section class="lab-section" id="setup"><div class="section-kicker">02 · Set up the CLI</div><h2>Put an agent in your terminal.</h2><p class="section-intro">Install Copilot CLI, sign in, and make your first request from an empty folder.</p><ol class="step-list"><li><span class="step-number">1</span><div>Install <a href="https://docs.github.com/copilot/how-tos/set-up/install-copilot-cli" target="_blank" rel="noopener">GitHub Copilot CLI</a> for your platform.</div></li><li><span class="step-number">2</span><div>Create and enter the project folder: <code>mkdir space-quiz &amp;&amp; cd space-quiz</code>.</div></li><li><span class="step-number">3</span><div>Run <code>copilot</code>, sign in, and trust the folder when prompted.</div></li><li><span class="step-number">4</span><div>Run <code>/model</code> and choose from the shared preference order below.</div></li></ol>${figure("assets/docs/copilot-cli-welcome.png", "Copilot CLI welcome screen showing the folder trust prompt and suggested slash commands", "The CLI greets you with the trust prompt and a few starting commands, including <code>/model</code>.")}${check("installed", "CLI installed and signed in")}${modelPanel()}<p class="note">Type <code>/</code> at any time to browse every available command, or <code>/help</code> for the full reference.</p></section>`],

    ["build", "Build", `<section class="tour-section" id="build"><div class="tour-marker"><span>01</span></div><div class="tour-content"><div class="tour-label">Build</div><h3>Build the quiz from the terminal</h3><p>Ask for the whole project in one detailed request, then review what the agent proposes before approving it.</p>${prompt("Create a space exploration quiz with 10 questions, a progress bar, score counter, and colorful animated feedback (green for correct, red shake for wrong). Show a results screen with an emoji reaction at the end. Single index.html, no server or dependencies. Accessible, keyboard-navigable, and respects prefers-color-scheme.", "Build the quiz")}<ol class="compact-steps"><li>Read the proposed plan and approve the file changes.</li><li>Run <code>/diff</code> to see exactly what changed in this session.</li><li>Open <code>index.html</code> in a browser and play a few questions.</li><li>Ask for one refinement, then run <code>/diff</code> again to confirm the change is scoped.</li></ol>${check("built", "Quiz built and reviewed")}</div></section>`],

    ["instructions", "Project instructions", `<section class="tour-section" id="instructions"><div class="tour-marker"><span>02</span></div><div class="tour-content"><div class="tour-label">Instructions</div><h3>Capture the rules with <code>/init</code></h3><p>With a working quiz on disk, generate agent instructions that describe the real project.</p><ol class="compact-steps"><li>Run <code>/init</code> in the session.</li><li>Review the generated instructions file before accepting it.</li><li>Keep only guidance that matches this project: single file, no dependencies, accessible, browser-tested.</li></ol><div class="warning"><strong>Order matters</strong><span><code>/init</code> reads the project as it exists right now. Running it after the quiz is built and polished produces instructions grounded in real code.</span></div>${check("instructions", "Agent instructions reviewed")}</div></section>`],

    ["test", "Test", `<section class="tour-section" id="test"><div class="tour-marker"><span>03</span></div><div class="tour-content"><div class="tour-label">Test</div><h3>Test before Git writes anything</h3><p>Prove the quiz works before a single commit exists.</p>${prompt("Run a browser-level smoke test for the quiz. Check keyboard navigation, score updates, correct and incorrect feedback, and the results screen. Report failures and fix them before continuing.", "Test the behavior")}<ol class="compact-steps"><li>Run the smoke test and read the agent’s report.</li><li>Fix failures and rerun until everything passes.</li><li>Use <code>!</code> to run a shell command directly, for example <code>!ls -la</code>, when you want to check something yourself.</li></ol>${check("tested", "Build and test passed before Git init")}</div></section>`],

    ["publish", "Publish", `<section class="tour-section" id="publish"><div class="tour-marker"><span>04</span></div><div class="tour-content"><div class="tour-label">Publish</div><h3>Initialize, commit, and publish</h3><p>Now that the project is tested, use Git and GitHub to share it.</p>${prompt("Initialize this folder as a Git repository, create an initial commit, and create a new public GitHub repository named space-quiz in my account. Push the current branch and set it as the default branch.", "Publish to GitHub")}<ol class="compact-steps"><li>Approve each Git and GitHub action as the agent requests it.</li><li>Run <code>!git log --oneline</code> to confirm the commit landed.</li><li>Open the repository and confirm the tested file is present.</li></ol>${check("published", "Repository published")}</div></section>`],

    ["issues", "Issues & sessions", `<section class="tour-section" id="issues"><div class="tour-marker"><span>05</span></div><div class="tour-content"><div class="tour-label">Issues &amp; sessions</div><h3>Work on issues in parallel</h3><p>Keep the backlog and the implementation loop in the terminal, and open separate sessions for independent work.</p>${prompt("Review the space quiz and create three focused GitHub issues with clear titles, user-focused descriptions, and acceptance criteria. Do not implement them yet.", "Create three issues")}<ol class="compact-steps"><li>Open the <strong>Issues</strong> tab to list and inspect the new issues.</li><li>Choose one issue, then press the <strong>left arrow</strong> to open the session side panel.</li><li>Use the panel to start another session for a different issue without losing this one.</li><li>In the new session, run <code>/worktree</code> to get an isolated worktree instead of branching in place.</li><li>Run <code>!git status</code> or <code>!git diff</code> whenever you want to inspect Git directly.</li><li>Run the smoke test again before opening a pull request.</li></ol>${check("issue", "Issue implemented and verified")}</div></section>`],

    ["plan", "Plan mode", `<section class="tour-section" id="plan"><div class="tour-marker"><span>06</span></div><div class="tour-content"><div class="tour-label">Plan mode</div><h3>Agree on the approach before any edits</h3><p>For the next issue, do not start with code. Plan mode researches the project and proposes an approach while leaving your files untouched.</p><ol class="compact-steps"><li>Start a session for a <strong>second issue</strong>.</li><li>Run <code>/plan</code> to switch the session into plan mode.</li><li>Send the issue and let the agent investigate without editing anything.</li><li>Read the plan, push back on anything missing, then approve it.</li><li>The session continues into implementation with the approved plan as its brief.</li></ol>${prompt("Plan how to implement this issue. Investigate the existing quiz, list the files you would change, call out risks to accessibility and the single-file constraint, and stop before making any edits.", "Ask for a plan")}<div class="callout"><div class="callout-icon">${icon("plan")}</div><div><strong>When plan mode pays off</strong><p>Use it for anything ambiguous, cross-cutting, or expensive to undo. The cheapest place to fix a bad approach is before the first edit.</p></div></div>${check("plan", "Plan reviewed and approved")}</div></section>`],

    ["context", "Context", `<section class="tour-section" id="context"><div class="tour-marker"><span>07</span></div><div class="tour-content"><div class="tour-label">Context</div><h3>Know what the agent can see</h3><p>Terminal commands make context visible and intentional.</p><ol class="compact-steps"><li>Run <code>/context</code> to inspect files, instructions, and conversation history.</li><li>Check how much of the window each part is consuming.</li><li>Run <code>/clear</code> to start fresh when the conversation has drifted.</li><li>Add the right file back before asking for another change.</li></ol>${figure("assets/docs/copilot-cli-context-usage.png", "Copilot CLI context usage panel breaking down tokens by system prompt, tools, messages, and free space", "<code>/context</code> shows exactly what is filling the context window.")}${check("context", "Context inspected")}</div></section>`],

    ["resume", "Resume & remote", `<section class="tour-section" id="resume"><div class="tour-marker"><span>08</span></div><div class="tour-content"><div class="tour-label">Resume</div><h3>Leave a session and come back later</h3><p>Sessions can be paused without losing their conversation or workspace context.</p><ol class="compact-steps"><li>Exit the current CLI session when you are ready to switch tasks.</li><li>From a terminal, run <code>copilot --resume</code> to pick a previous session.</li><li>Inside Copilot CLI, use <code>/resume</code> to jump between sessions without leaving the CLI.</li><li>Confirm the restored session still has the expected files, issue context, and model.</li></ol><h4>Take it further with <code>/remote</code></h4><p>Once the local loop feels natural, run <code>/remote</code> to hand a session to a GitHub-hosted cloud agent, close your laptop, and follow its progress from GitHub. Save this for long, well-specified work.</p>${check("resume", "Session resumed")}</div></section>`],

    ["review", "Pull request", `<section class="tour-section" id="review"><div class="tour-marker"><span>09</span></div><div class="tour-content"><div class="tour-label">Pull request</div><h3>Create, review, and merge from the CLI</h3><p>Finish the development loop without switching to a desktop UI.</p><ol class="compact-steps"><li>Run <code>/diff</code> to inspect the changed files one last time.</li><li>Ask Copilot to create a pull request from the current branch, or run <code>/pr create</code>.</li><li>Open the <strong>Pull requests</strong> tab to check the title, description, files, and status checks.</li><li>Fix actionable feedback, rerun the smoke test, and reply with what changed.</li><li>When it is ready, run <code>/pr agentmerge</code> to validate the pull request and merge it after the required confirmations and checks pass.</li></ol>${check("reviewed", "Pull request reviewed and merged")}</div></section>`],

    ["delegate", "Delegate & cloud", `<section class="tour-section last" id="delegate"><div class="tour-marker"><span>10</span></div><div class="tour-content"><div class="tour-label">Go further</div><h3>Delegate work once you trust the loop</h3><p>You have shipped the feature. Now that you know what good output looks like, some tasks are worth running beside you rather than in front of you.</p><ol class="compact-steps"><li>Run <code>/delegate</code> to send a focused accessibility or test task to another agent.</li><li>Keep working in the primary session while it runs.</li><li>Compare the delegated result against your session before accepting it.</li><li>For a larger, well-specified issue, start a <strong>cloud session</strong> and follow its progress from the CLI.</li></ol>${check("delegate", "Delegated work reviewed")}</div></section>`]
  ],

  renderResources() {
    return `<section class="lab-section finish-section" id="resources"><div class="section-kicker">03 · Review &amp; resources</div><div class="finish-badge">${icon("terminal")}</div><h2>You’ve completed the CLI route.</h2><p class="section-intro">You built, tested, published, ran sessions in parallel, planned before editing, delegated, resumed, and merged a pull request without leaving the terminal.</p><div class="recap-grid"><div><span>01</span><strong>Built</strong><small>Then tested</small></div><div><span>02</span><strong>Planned</strong><small>Before editing</small></div><div><span>03</span><strong>Merged</strong><small>With /pr agentmerge</small></div></div>${check("complete", "Mark the lab complete", "Progress is saved for Copilot CLI only.")}</section>`;
  },

  render() {
    return sharedOverview(this) + this.sections.map(([, , html]) => html).join("") + this.renderResources();
  }
};
