import { sharedOverview, prompt, check, modelPanel } from "./shared.js";
export const vscodeLab = {
  id: "vscode", name: "Copilot in VS Code", title: "Copilot in VS Code",
  intro: "Use the editor loop: build in a workspace, inspect context from the bottom-right, test before Git writes, and preview the result in VS Code’s integrated browser.",
  preview: "I’ll build in the editor, inspect context from the bottom-right, and test before publishing.",
  sections: [
    ["setup", "Set up", `<section class="lab-section" id="setup"><div class="section-kicker">02 · Set up VS Code</div><h2>Bring Copilot into the editor.</h2><p class="section-intro">Install VS Code, GitHub Copilot, and the GitHub Pull Requests and Issues extension. There is no Node.js prerequisite.</p><ol class="step-list"><li><span class="step-number">1</span><div>Install <a href="https://code.visualstudio.com/" target="_blank" rel="noopener">VS Code</a> and the GitHub Copilot extensions.</div></li><li><span class="step-number">2</span><div>Install the official <a href="https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github" target="_blank" rel="noopener">GitHub Pull Requests and Issues</a> extension.</div></li><li><span class="step-number">3</span><div>Sign in to GitHub, open an empty <code>space-quiz</code> folder, and choose the shared model order.</div></li><li><span class="step-number">4</span><div>Open the integrated browser from VS Code to preview the project without leaving the editor.</div></li></ol>${check("installed", "VS Code and GitHub integrations ready")}${modelPanel()}</section>`],
    ["build", "Build", `<section class="tour-section" id="build"><div class="tour-marker"><span>01</span></div><div class="tour-content"><div class="tour-label">Build</div><h3>Build in the workspace</h3><p>Keep the editor, chat, files, and preview together.</p>${prompt("Create a colorful, accessible space exploration quiz with 10 questions in a single index.html. Use no server or dependencies. Open it in the VS Code integrated browser.", "Build the quiz")}<ol class="compact-steps"><li>Review the generated file in the editor.</li><li>Open the integrated browser and play several questions.</li><li>Make one refinement with Copilot Chat and confirm the preview updates.</li><li>Once the base quiz works, run <code>/init</code> in Copilot Chat to create project agent instructions.</li><li>Review the generated instructions and keep the guidance aligned with the quiz’s accessibility, testing, and single-file constraints.</li></ol>${check("built", "Quiz built, initialized, and previewed")}</div></section>`],
    ["context", "Inspect context", `<section class="tour-section" id="context"><div class="tour-marker"><span>02</span></div><div class="tour-content"><div class="tour-label">Context</div><h3>Inspect context from the bottom-right</h3><p>VS Code makes the active context available at the bottom-right of the Copilot surface.</p><ol class="compact-steps"><li>Open the Copilot context indicator in the <strong>bottom-right</strong>.</li><li>Inspect the files, workspace instructions, and symbols included in the request.</li><li>Remove irrelevant context or add the quiz file before continuing.</li></ol>${check("context", "Bottom-right context inspected")}</div></section>`],
    ["test", "Test", `<section class="tour-section" id="test"><div class="tour-marker"><span>03</span></div><div class="tour-content"><div class="tour-label">Test</div><h3>Build and test before Git writes</h3><p>Use the integrated browser and a smoke-test prompt before initializing or committing Git.</p>${prompt("Run a browser-level smoke test for the quiz. Check keyboard navigation, score updates, correct and incorrect feedback, and the results screen. Fix any failures, then report what passed.", "Test the behavior")}<ol class="compact-steps"><li>Run the smoke test and check the integrated browser.</li><li>Fix failures and rerun until green.</li><li>Only after build/test passes, initialize Git, commit, create the remote, and push.</li></ol>${check("tested", "Build/test passed before Git init")}</div></section>`],
    ["publish", "Publish", `<section class="tour-section" id="publish"><div class="tour-marker"><span>04</span></div><div class="tour-content"><div class="tour-label">Publish</div><h3>Initialize, commit, and publish</h3><ol class="compact-steps"><li>Initialize Git and create an initial commit from Source Control.</li><li>Use <strong>Publish Branch</strong> or <strong>Publish to GitHub</strong> to create the remote and push the branch.</li><li>Confirm the tested file is present on GitHub.</li></ol>${check("published", "Repository published")}</div></section>`],
    ["mcp", "GitHub MCP", `<section class="tour-section" id="mcp"><div class="tour-marker"><span>05</span></div><div class="tour-content"><div class="tour-label">GitHub MCP</div><h3>Give Copilot GitHub-aware tools</h3><p>Enable the GitHub MCP server before asking Copilot to create issues or work with pull requests.</p><ol class="compact-steps"><li>Open VS Code Settings and enable the built-in <strong>GitHub MCP</strong> server if it is available in your version.</li><li>If your installation does not include it, install a trusted GitHub MCP server from the MCP/server configuration flow and review the tools and permissions it requests.</li><li>Confirm the GitHub tools are available in Copilot Chat before continuing.</li></ol>${check("mcp", "GitHub MCP enabled and reviewed")}</div></section>`],
    ["issues", "Issues & PRs", `<section class="tour-section" id="issues"><div class="tour-marker"><span>06</span></div><div class="tour-content"><div class="tour-label">Issues &amp; pull requests</div><h3>Plan and implement from VS Code</h3><p>Use the GitHub MCP tools, GitHub view, and Copilot Agent mode together.</p>${prompt("Review the space quiz and suggest three focused feature ideas. Use the GitHub tools to create a separate issue for each with a clear title, user-focused description, and acceptance criteria. Do not implement them yet.", "Create three issues")}<ol class="compact-steps"><li>Open the GitHub view in the Activity Bar and inspect the new issues.</li><li>Choose one issue, then select the <strong>+</strong> button in Copilot Chat to start a new session for it.</li><li>Use Agent mode to implement the issue in the new session and keep the original session available for comparison.</li><li>Run the integrated-browser smoke test before creating a pull request.</li></ol>${check("issue", "Issue implemented and verified")}</div></section>`],
    ["review", "Review & merge", `<section class="tour-section last" id="review"><div class="tour-marker"><span>07</span></div><div class="tour-content"><div class="tour-label">Review &amp; merge</div><h3>Inspect, review, and merge with GitHub tools</h3><ol class="compact-steps"><li>Open the Git integration windows in VS Code to inspect the changed files and diff before creating the PR.</li><li>Ask Copilot to create the pull request, or create it from Source Control or the GitHub view.</li><li>Review the changed files and checks in VS Code, then open the PR on GitHub when you want the full review surface.</li><li>Ask Copilot with GitHub MCP to inspect the PR, resolve merge conflicts, address review comments, and investigate failing CI checks.</li><li>Retest in the integrated browser, review every proposed change, and update the branch.</li><li>When the required checks and review are complete, merge from the GitHub integration or GitHub itself.</li></ol>${check("reviewed", "Pull request reviewed and merged")}</div></section>`]
  ],
  renderResources() { return `<section class="lab-section finish-section" id="resources"><div class="section-kicker">03 · Review & resources</div><div class="finish-badge">✦</div><h2>You’ve completed the VS Code route.</h2><p class="section-intro">You built in the editor, inspected context, tested in the integrated browser, and published with confidence.</p>${check("complete", "Mark the lab complete", "Progress is saved for VS Code only.")}</section>`; },
  render() { return sharedOverview(this.title, this.intro) + this.sections.map(([, , html]) => html).join("") + this.renderResources(); }
};
