import { sharedOverview, prompt, check, modelPanel, icon, figure } from "./shared.js";

export const vscodeLab = {
  id: "vscode",
  name: "VS Code",
  title: "Copilot in VS Code",
  needsGit: true,
  policy: false,
  intro: "Use the editor loop: build in a workspace, inspect context from the bottom-right, test before Git writes, plan before you edit, and let GitHub tools handle issues and pull requests without leaving VS Code.",
  preview: "I’ll build in the editor, inspect context from the bottom-right, and test before publishing.",
  sections: [
    ["setup", "Set up", `<section class="lab-section" id="setup"><div class="section-kicker">02 · Set up VS Code</div><h2>Bring Copilot into the editor.</h2><p class="section-intro">Install VS Code, GitHub Copilot, and the GitHub Pull Requests and Issues extension.</p><ol class="step-list"><li><span class="step-number">1</span><div>Install <a href="https://code.visualstudio.com/" target="_blank" rel="noopener">VS Code</a> and sign in to GitHub.</div></li><li><span class="step-number">2</span><div>Open the Extensions view and install <strong>GitHub Copilot</strong> and <strong>GitHub Copilot Chat</strong>.</div></li><li><span class="step-number">3</span><div>Install the official <a href="https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github" target="_blank" rel="noopener">GitHub Pull Requests and Issues</a> extension.</div></li><li><span class="step-number">4</span><div>Open an empty <code>space-quiz</code> folder and pick a model from the shared order below.</div></li></ol>${figure("assets/docs/vscode-extension-search.png", "The VS Code Extensions view with the GitHub Copilot extension in the search results", "Search the Extensions view to install the Copilot and GitHub extensions.")}${check("installed", "VS Code and GitHub integrations ready")}${modelPanel()}</section>`],

    ["build", "Build", `<section class="tour-section" id="build"><div class="tour-marker"><span>01</span></div><div class="tour-content"><div class="tour-label">Build</div><h3>Build in the workspace</h3><p>Keep the editor, chat, files, and preview together.</p>${prompt("Create a colorful, accessible space exploration quiz with 10 questions in a single index.html. Add a progress bar, score counter, animated correct and incorrect feedback, and a results screen. Use no server or dependencies. Open it in the VS Code integrated browser.", "Build the quiz")}<ol class="compact-steps"><li>Review the generated file in the editor.</li><li>Open the integrated browser and play several questions.</li><li>Ask for one refinement in Copilot Chat and confirm the preview updates.</li><li>Open Source Control to see the changed files and diff at any point.</li></ol>${check("built", "Quiz built and previewed")}</div></section>`],

    ["instructions", "Project instructions", `<section class="tour-section" id="instructions"><div class="tour-marker"><span>02</span></div><div class="tour-content"><div class="tour-label">Instructions</div><h3>Capture the rules with <code>/init</code></h3><p>With a working quiz in the workspace, generate repository custom instructions that describe the real project.</p><ol class="compact-steps"><li>Run <code>/init</code> in Copilot Chat.</li><li>Review the generated <code>.github/copilot-instructions.md</code> before saving it.</li><li>Keep only guidance that matches this project: single file, no dependencies, accessible, browser-tested.</li></ol>${figure("assets/docs/custom-instructions-vscode.png", "A copilot-instructions.md file open in VS Code showing repository custom instructions", "Repository custom instructions live in <code>.github/copilot-instructions.md</code> and apply to every chat request.")}<div class="warning"><strong>Order matters</strong><span><code>/init</code> reads the workspace as it exists right now. Running it after the quiz is built produces instructions grounded in real code.</span></div>${check("instructions", "Custom instructions reviewed")}</div></section>`],

    ["context", "Inspect context", `<section class="tour-section" id="context"><div class="tour-marker"><span>03</span></div><div class="tour-content"><div class="tour-label">Context</div><h3>Inspect context from the bottom-right</h3><p>VS Code shows the active context at the bottom-right of the Copilot Chat input.</p><ol class="compact-steps"><li>Open the context indicator in the <strong>bottom-right</strong> of the chat box.</li><li>Inspect the files, custom instructions, and symbols included in the request.</li><li>Remove irrelevant context or attach the quiz file before continuing.</li></ol>${check("context", "Bottom-right context inspected")}</div></section>`],

    ["test", "Test", `<section class="tour-section" id="test"><div class="tour-marker"><span>04</span></div><div class="tour-content"><div class="tour-label">Test</div><h3>Build and test before Git writes</h3><p>Use the integrated browser and a smoke-test prompt before initializing or committing Git.</p>${prompt("Run a browser-level smoke test for the quiz. Check keyboard navigation, score updates, correct and incorrect feedback, and the results screen. Fix any failures, then report what passed.", "Test the behavior")}<ol class="compact-steps"><li>Run the smoke test and check the integrated browser.</li><li>Fix failures and rerun until green.</li><li>Only after build and test pass, move on to Git.</li></ol>${check("tested", "Build and test passed before Git init")}</div></section>`],

    ["publish", "Publish", `<section class="tour-section" id="publish"><div class="tour-marker"><span>05</span></div><div class="tour-content"><div class="tour-label">Publish</div><h3>Initialize, commit, and publish</h3><p>Do this entirely through the built-in Git integration.</p><ol class="compact-steps"><li>Open <strong>Source Control</strong> and choose <strong>Initialize Repository</strong>.</li><li>Stage the files, write a commit message, and commit.</li><li>Choose <strong>Publish Branch</strong> and create a public <code>space-quiz</code> repository on GitHub.</li><li>Confirm the tested file is present on GitHub.</li></ol>${check("published", "Repository published")}</div></section>`],

    ["plan", "Plan mode", `<section class="tour-section" id="plan"><div class="tour-marker"><span>06</span></div><div class="tour-content"><div class="tour-label">Plan mode</div><h3>Agree on the approach before any edits</h3><p>Plan mode researches the workspace and writes an implementation plan without touching your files.</p><ol class="compact-steps"><li>Open Copilot Chat and use the <strong>mode dropdown</strong> above the input.</li><li>Switch from Agent to <strong>Plan</strong>.</li><li>Describe the next feature and let Copilot investigate the workspace.</li><li>Read the plan, request changes, then switch back to <strong>Agent</strong> to implement it.</li></ol>${prompt("Plan how to add a review screen that shows every question with the answer I chose. Investigate the existing quiz, list the changes you would make, call out accessibility and single-file risks, and stop before editing.", "Ask for a plan")}<div class="callout"><div class="callout-icon">${icon("plan")}</div><div><strong>When plan mode pays off</strong><p>Use it for anything ambiguous, cross-cutting, or expensive to undo. The cheapest place to fix a bad approach is before the first edit.</p></div></div>${check("plan", "Plan reviewed and approved")}</div></section>`],

    ["mcp", "GitHub MCP", `<section class="tour-section" id="mcp"><div class="tour-marker"><span>07</span></div><div class="tour-content"><div class="tour-label">GitHub MCP</div><h3>Give Copilot GitHub-aware tools</h3><p>Enable the GitHub MCP server <em>before</em> asking Copilot to create issues or work with pull requests.</p><ol class="compact-steps"><li>Open VS Code Settings and enable the built-in <strong>GitHub MCP</strong> server if your version includes it.</li><li>Otherwise, install a trusted GitHub MCP server through the MCP server configuration flow.</li><li>Review the tools and permissions the server requests before approving it.</li><li>Confirm the GitHub tools appear in the Copilot Chat tools picker.</li></ol>${check("mcp", "GitHub MCP enabled and reviewed")}</div></section>`],

    ["issues", "Issues & sessions", `<section class="tour-section" id="issues"><div class="tour-marker"><span>08</span></div><div class="tour-content"><div class="tour-label">Issues &amp; sessions</div><h3>Plan and implement from VS Code</h3><p>With GitHub MCP enabled, Copilot can create and read issues directly.</p>${prompt("Review the space quiz and suggest three focused feature ideas. Use the GitHub tools to create a separate issue for each with a clear title, user-focused description, and acceptance criteria. Do not implement them yet.", "Create three issues")}<ol class="compact-steps"><li>Open the GitHub view in the Activity Bar and inspect the new issues.</li><li>Choose one issue, then select the <strong>+</strong> button in Copilot Chat to start a new session for it.</li><li>Use Agent mode to implement the issue while keeping the original session available for comparison.</li><li>Run the integrated-browser smoke test before creating a pull request.</li></ol>${check("issue", "Issue implemented and verified")}</div></section>`],

    ["review", "Review & merge", `<section class="tour-section last" id="review"><div class="tour-marker"><span>09</span></div><div class="tour-content"><div class="tour-label">Review &amp; merge</div><h3>Inspect, review, and merge with GitHub tools</h3><ol class="compact-steps"><li>Open <strong>Source Control</strong> to inspect the changed files and diff before creating the PR.</li><li>Ask Copilot to create the pull request, or create it from Source Control or the GitHub view.</li><li>Review the changed files and checks in VS Code, then open the PR on GitHub for the full review surface.</li><li>Ask Copilot with GitHub MCP to inspect the PR, resolve merge conflicts, address review comments, and investigate failing CI checks.</li><li>Retest in the integrated browser, review every proposed change, and update the branch.</li><li>When checks and review are complete, ask the agent to merge, or merge from the GitHub integration.</li></ol>${check("reviewed", "Pull request reviewed and merged")}</div></section>`]
  ],

  renderResources() {
    return `<section class="lab-section finish-section" id="resources"><div class="section-kicker">03 · Review &amp; resources</div><div class="finish-badge">${icon("preview")}</div><h2>You’ve completed the VS Code route.</h2><p class="section-intro">You built in the editor, captured instructions, tested in the integrated browser, planned before editing, and merged with GitHub tools.</p><div class="recap-grid"><div><span>01</span><strong>Built</strong><small>Then tested</small></div><div><span>02</span><strong>Planned</strong><small>Before editing</small></div><div><span>03</span><strong>Merged</strong><small>With GitHub MCP</small></div></div>${check("complete", "Mark the lab complete", "Progress is saved for VS Code only.")}</section>`;
  },

  render() {
    return sharedOverview(this) + this.sections.map(([, , html]) => html).join("") + this.renderResources();
  }
};
